import Head from "next/head";
import Image from "next/image";
import { TutorialList } from "@/stories/TutorialList";

import styles from "@/styles/Home.module.css";

export default function Home() {
  return (
    <>
      <Head>
        <title>With Map API</title>
        <meta name="description" content="Generated by miku" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.description}>
          <p>方向音痴の人がすべき事前準備</p>
          <div>By MegumiTok</div>
        </div>

        <div className={styles.center}>
          <Image
            className={styles.logo}
            src="/icon.png"
            alt="Next.js Logo"
            width={400}
            height={400}
            priority
          />
        </div>

        <TutorialList />
      </main>
    </>
  );
}
